name: Build & Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: deploy all microservices
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{secrets.SSH_KEY }}
          username: ${{ secrets.SSH_NAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf MICRO-NODES-PROD
            mkdir MICRO-NODES-PROD
            cd MICRO-NODES-PROD
            echo 'Wiped previous version'
            GIT_SSL_NO_VERIFY=true git clone https://github.com/andreachirico11/micro-nodes.git
            echo 'Cloned from git'
            cp ../ENVIRONMENTS/micro-nodes-prod/.env.compose micro-nodes/.env.compose
            echo 'Env copied'
            cp -r ../SSL_CERTS/nodemicrosss micro-nodes/ssl-certs
            echo 'Certs Copied'
            cd micro-nodes
            docker-compose build --no-cache
            docker compose up -d --force-recreate
            

